import { STUDIO } from "@/lib/art";

/**
 * Helpers for the dynamic Open Graph cards generated by `/api/og`
 * (Edge Function, see `app/api/og/route.tsx`).
 */

export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

export type OgCardParams = {
  /** Artwork slug from `lib/art.ts` — fills title, technique, price and photo. */
  slug?: string;
  title?: string;
  subtitle?: string;
  eyebrow?: string;
  price?: string;
  badge?: string;
};

/** Relative URL of a generated card — `metadataBase` makes it absolute. */
export function ogCardUrl(params: OgCardParams = {}): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string" && value.trim()) search.set(key, value);
  }
  const query = search.toString();
  return query ? `/api/og?${query}` : "/api/og";
}

/** Ready-to-use `openGraph.images` entry (absolute once `metadataBase` is set). */
export function ogCard(params: OgCardParams = {}, alt?: string) {
  return {
    url: ogCardUrl(params),
    width: OG_WIDTH,
    height: OG_HEIGHT,
    type: "image/png",
    alt: alt ?? `${STUDIO.name} — ${STUDIO.tagline}`,
  };
}

/** Matching Twitter/X `summary_large_image` block for a card. */
export function twitterCard(
  params: OgCardParams = {},
  alt?: string,
): { card: "summary_large_image"; images: { url: string; alt: string }[] } {
  return {
    card: "summary_large_image",
    images: [{ url: ogCardUrl(params), alt: alt ?? `${STUDIO.name}` }],
  };
}

/**
 * OG + Twitter image blocks for a page in one call — spread into `metadata`:
 *
 * ```ts
 * export const metadata: Metadata = {
 *   title: "Galeria prac",
 *   ...socialMetadata({ eyebrow: "Kolekcja" }),
 * };
 * ```
 */
export function socialMetadata(params: OgCardParams = {}, alt?: string) {
  return {
    openGraph: { images: [ogCard(params, alt)] },
    twitter: twitterCard(params, alt),
  };
}
